swagger: '2.0'
info:
  version: 1.0.0
  title: Customer Service RESTful API
  description: Customer Service RESTful API
schemes:
- http
host: localhost:8080
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /customer:
    get:
      tags:
        - customer
      summary: Find customer by ID
      description: Returns a single customer
      operationId: getCustomerById
      produces:
        - application/hal+json
      parameters:
        - name: id
          in: path
          description: ID of customer to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Customer'
        '400':
          description: Invalid ID supplied
        '404':
          description: Customer not found

definitions:
  Id:
    type: integer
    format: int64
  Name:
    type: object
    properties:
      firstName:
        type: string
        description: Customer First Name
      middleName:
        type: string
        description: Customer Middle Name
      lastName:
        type: string
        description: Customer Last Name
  Customer:
      type: object
      required:
        - id
      discriminator: customerType
      properties:
        id:
          description: Customer ID
          allOf:
            - $ref: '#/definitions/Id'
        name:
          type: object
          description: Customer Name
          allOf:
            - $ref: '#/definitions/Name'
        status:
          type: string
          description: Customer status
          enum:
            - active
            - inactive